Repository CMU-313/fall22-hw3-team-vasa, pull requests merged in 2022-10, with the labels that each got.

#20 Resolves #18 and other cosmetic changes to button and applicant table
  docs-web/src/main/webapp/src/app/docs/app.js
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/dashboard.html
  docs-web/src/main/webapp/src/partial/docs/document.html
Labels: enhancement

#22 Fixed failing tests and added more unit tests
  .teedy.png.icloud
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
  docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestJpa.java
  docs-core/src/test/resources/file/.apache.pptx.icloud
  docs-core/src/test/resources/file/apache.pptx
  docs-web/src/test/resources/file/.apache.pptx.icloud
  docs-web/src/test/resources/file/apache.pptx
  teedy.png
Labels: testing

#23 Resolves #16: Update Applicant Status in Database with added tweaks to the documentDao file to record updates for documents regarding the status
  docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
  docs-web/src/main/webapp/src/partial/docs/document.html
Labels: enhancement

#27 Resolves #26 so that new applicant status is shown in the language input
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/resources/db/update/dbupdate-000-0.sql
  docs-core/src/main/resources/db/update/dbupdate-012-0.sql
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
  docs-web/src/main/webapp/src/app/docs/app.js
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/document.edit.html
  docs-web/src/main/webapp/src/partial/docs/document.html
Labels: enhancement

#28 Cleaned out the white space from my last commit
  docs-web/src/main/webapp/src/partial/docs/document.edit.html
Labels: documentation
